### ISSUE TITLE
Control flow for loading/overwriting/copying settings

### ISSUE THREAD

**Issue by DerekRobin** [devxp-ca/devxp#166]
<del>If a user selects a repo with a pre-existing database entry, just prompt them:
```That repo has settings already saved. Would you like to overwrite them? YES/NO?```
If they select YES, then give them another prompt:
```Are you sure you would like to overwrite your saved settings? YES/NO```
If yes, overwrite the settings.
If no, populate the settings panel with their saved settings.</del>

UPDATE:
- [x] Upon selecting a repo, if the repo has saved settings, the user is prompted:
`That repo has settings already saved. Would you like to load them? This will undo any unsaved changes. YES/NO?`
Upon yes, we should pull the saved settings and refresh the page.
Upon no, do nothing but change the currently selected repo.

- [ ] Then regardless of what they choose (i.e. as a separate task), when they press the submit button, if the repo already has settings saved, we ask them:
`That repo has settings already saved. Would you like to overwrite them? YES/NO?`
Upon yes, bring up the current modal prompt (i.e. `Are you sure you want to submit?`)
Upon no, remove the modal, and keep the temporary settings as they are.

- [x] Upon selecting the "copy to another repo" button, a modal should inform the user: `Are you sure you want to copy settings from [source_repo_name] to [destination_repo_name]? Any unsubmitted settings in the current repo will be ignored, and the settings of the destination repo will be overwritten. `

**Comment by keanelekenns** [comment]
We could definitely do it this way, but I wonder if it would be more clear to put the overwrite message when they click submit rather than select the repo. This is because you could theoretically choose a repo, then choose not to load its saved settings, and then configure something, but if you do not submit those new settings, they are not overwritten. So maybe it could be something like:

Upon selecting a repo, if the repo has saved settings, the user is prompted:
`That repo has settings already saved. Would you like to load them? YES/NO?`
Then regardless of what they choose, when they press the submit button, if the repo already has settings saved, we ask them:
`That repo has settings already saved. Would you like to overwrite them? YES/NO?`

**Comment by DerekRobin** [comment]
Ah yeah I think that might be a better idea

**Comment by DerekRobin** [comment]
Closed as this is the same as #148

**Comment by keanelekenns** [comment]
I don't think this was encompassed by #148 as far as I can see. These prompts still need to exist.
